blog/urls.py
from django.urls import path

from django.views.generic import TemplateView
from . import views

app_name = 'blog'

urlpatterns = [
    path('blog/<slug:slug>/', views.BlogDetailView.as_view(), name='detail'),
    path('blog/edit/<int:blog_id>/', views.BlogEditView.as_view(), name='edit'),
    path('blog/delete/<int:blog_id>/', views.delete_blog, name='delete'),
    path('write-new-blog/', views.BlogCreateView.as_view(), name='submit'),
    path('submit/success/', TemplateView.as_view(template_name='blog/submit-success.html'), name='submit-success'),
    path('search/<str:query>/', views.SearchBlogsListView.as_view(), name='search'),
    path('comment/<int:blog_id>/', views.comment, name='comment'),
    path('nwb/', views.NWBView.as_view(), name='nwb'),
]

home/urls.py
from django.urls import path

from django.views.generic import TemplateView
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.BlogListView.as_view(), name='index'),
    path('tag/<str:tag>/', views.TagListView.as_view(), name='tag_page'),
    path('tag/search/<str:query>/', views.tag_search, name='tag_search'),
    path('rss/', views.RSSBlogFeedView(), name='rss_feed'),
    path('subscribe/', views.subscribe, name='subscribe'),
    path('unsubscribe/', views.unsubscribe, name='unsubscribe'),
    path('about/', TemplateView.as_view(template_name='home/about.html'), name='about'),
    path('contact/', TemplateView.as_view(template_name='home/contact.html'), name='contact'),
    path('support/', TemplateView.as_view(template_name='home/support.html'), name='support'),
    path('credits/', TemplateView.as_view(template_name='home/credits.html'), name='credits'),
    path('faqs/', views.FaqListView.as_view(), name='faqs'),
    path('privacy-policy/', TemplateView.as_view(template_name='home/privacy-policy.html'), name='privacy_policy'),
    path('terms/', TemplateView.as_view(template_name='home/terms.html'), name='terms'),
]

home/models.py
from django.db import models

from django.utils.crypto import get_random_string

# Create your models here.

class Subscriber(models.Model):
    email = models.EmailField(default='', max_length=100, blank=False)
    token = models.CharField(max_length=50, default='', blank=False)
    date = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.email
    
    def save(self, *args, **kwargs):
        if not self.id:
            self.token = get_random_string(length=16)
        super(Subscriber, self).save(*args, **kwargs)

class SpecialBlog(models.Model):
    slug = models.CharField(max_length=200, blank=False, default='')
    speciality = models.CharField(choices=(('featured', 'Featured'), ('nwb', 'NWB')), max_length=50, blank=False)

    def __str__(self):
        return self.slug

class Faq(models.Model):
    question = models.CharField(max_length=200)
    answer = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.question

    class Meta:
        ordering = ('-created_at',)

home/views.py
from django.http import JsonResponse
from django.shortcuts import render
from django.views.generic import ListView
from django.contrib.syndication.views import Feed
from django.urls import reverse_lazy, reverse

from home.models import Faq, Subscriber, SpecialBlog
from blog.models import Blog, Tag

from config import BRAND_NAME

# Create your views here.

class BlogListView(ListView):
    model = Blog
    template_name = 'home/index.html'
    context_object_name = 'blogs'
    paginate_by = 10

    success_url = reverse_lazy('home:thank_you')
    success_message = 'Thanks for subscribing our newletter, stay tuned!'

    def get_queryset(self):
        # Call the base implementation first to get a context
        blogs = super(BlogListView, self).get_queryset()
        # Add extras
        blogs = blogs[:108]
        return blogs

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(BlogListView, self).get_context_data(**kwargs)
        # Add extras
        slugs = [blog.slug for blog in SpecialBlog.objects.filter(speciality='featured')]
        context['featured_blogs'] = Blog.objects.filter(slug__in=slugs)

        return context


class TagListView(ListView):
    model = Blog
    template_name = 'home/tag.html'
    context_object_name = 'blogs'
    paginate_by = 12

    def get_queryset(self):
        # Call the base implementation first to get a context
        blogs = super(TagListView, self).get_queryset()
        # Add extras
        tag = self.kwargs['tag']
        blogs = blogs.filter(tags__name__in=[tag])[:108]
        return blogs

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(TagListView, self).get_context_data(**kwargs)
        # Add extras
        context['tag'] = self.kwargs['tag']
        return context


class RSSBlogFeedView(Feed):
    title = BRAND_NAME
    link = "/blog/"
    description = f"RSS feed of {BRAND_NAME}"
 
    def items(self, user):
        return Blog.objects.all()
 
    def item_title(self, item):
        return item.title
       
    def item_description(self, item):
        from html import unescape
        from django.utils.html import strip_tags
        
        return unescape(strip_tags(item.body))
 
    def item_link(self, item):
       return reverse('blog:detail', args=[item.slug])

class FaqListView(ListView):
    model = Faq
    template_name = 'home/faq.html'
    context_object_name = 'faqs'
    paginate_by = 7

def tag_search(request, query):
    if len(query) > 2:
        data = {
            'suggestions': [tag.name for tag in Tag.objects.filter(name__icontains=query)]
        }
    else:
        data = {'suggestions': []}
    return JsonResponse(data)

def subscribe(request):
    if request.method == 'POST':
        email = request.POST.get('subscribe_email')
        
        if not Subscriber.objects.filter(email=email).exists():
            subscriber = Subscriber(email=email)
            subscriber.save()

        return render(request, 'home/subscribe.html', {'email': email, 'is_submitted': True})
    return render(request, 'home/subscribe.html')


def unsubscribe(request):
    if request.method == 'POST':
        email = request.POST.get('unsubscribe_email')
        Subscriber.objects.filter(email=email).delete()

        return render(request, 'home/unsubscribe.html', {'email': email, 'is_submitted': True})
    return render(request, 'home/unsubscribe.html')

home/templates/home/about.html
{% extends 'home/base.html' %}
{% load static %}
{% load home_tags %}

{% block meta %}
{% include 'home/components/~common/meta.html' with meta_title='{{ brand_name }}' meta_desc='{{ brand_name }} is an Indian non-profit organization that publishes news, disclosures, classified media provided by sources, media critique, reportage and satirical views on current happenings around. It was founded in 2021 by Vaibhav Shukla in India under the holding company MRVAIBH Inc., started in 2019 that has been providing multi-sector benefits for the last 2 years.' %}
{% endblock meta %}

{% block title %} About Us | {{ brand_name }} {% endblock title %}

{% block css %}
.content-media img {
  max-height: 300px;
  width: auto;
}
.content-media h1 {
  position: relative;
  left: 0.8em;
  margin-top: 2em;
  text-align: left;
}
.drop-cap::first-letter {
  padding-top: 1rem;
}
@media all and (max-width: 820px) {
  .content-media {
    display: flex;
    flex-direction: column;
    align-items: center;
  }
  .content-media h1 {
    left: unset;
    text-align: center;
    margin-top: 0.8em;
  }
}
{% endblock css %}

{% block body %}
<!-- content
   ================================================== -->
<section id="content-wrap" class="site-page">
  <div class="row">
    <div class="col-twelve">
      <section>

        <div class="row content-media">
          <img class="col-six tab-full" src="{% static 'home/images/'|add:brand_logo %}" />
          <h1 class="entry-title col-six tab-full" style="font-size: 3.3em">{% brand_name_cased %}</h1>
        </div>

        <div class="primary-content">

          <p class="drop-cap">
            &nbsp;{{ brand_name }} is an Indian non-profit organization
            that publishes classified media provided by the people of the community.
            It provides media, publication, news, reportage and satirical commentary.
            It was founded in 2021 by <a href="https://en.everybodywiki.com/MrVaiBH">Vaibhav Shukla</a> in India under it's parent company <a href="https://mrvaibh.herokuapp.com">MRVAIBH Inc.</a>, started in 2019 that had provided multi-sector benefits in its first 2 years.
          </p>

          <p>
            Transparent and open source, {{ brand_name }} is a platform for the public to share their knowledge, views and opinions.
            It publishes pertinent articles which can also be voted by regular users of the internet.
            It is different from other publications as it's 100% non-profit and does not earn money, the only vision behind NW is to provide a free platform for free voice.
          </p>

          <h1 class="entry-title add-bottom">What NT is NOT?</h1>

          <p>
            {{ brand_name }} is not a propaganda or propaganda-related website.
            It is not meant to spread extreme hate &lpar;or even love&rpar; on government, politics or any cultural belief.
          </p>

          <div class="row block-1-2 block-tab-full">
            <div class="bgrid">
              <h3>non-profit.</h3>
              <p>The organization is independent of any source of revenue other than <a href="https://buymeacoffee.com/mrvaibh" target="_blank">BuyMeACoffee.com</a> support. There are NO ads, as we don't intend to sell our supporters' data and our self-esteem to advertisers. We do not demand any other donation than your precious time and support.</p>
            </div>

            <div class="bgrid">
              <h3>free voice.</h3>
              <p>Not for the sake of saying, but for the sake of democracy, we actually believe in free voice. All the blogs, media and other terms of information go through our <a href="/editing-policies">Editing Policies</a>. Come, join us, we HAVE to save our <a href="https://www.lawctopus.com/academike/freedom-of-speech-and-expression/" target="_blank">Right to Freedom of Speech</a> culture.</p>
            </div>

            <div class="bgrid">
              <h3>neutrality meter.</h3>
              <p>Like no other media company, we do have a fool-proof methodology to calculate the neutrality &lpar;how unbiased&rpar; of an information. The scale is between 1 to 10 and literally anyone &lpar;who is an <abbr title="An active registered individual on {{ brand_name }}">NTian</abbr>&rpar; can vote for it. Also, there are no chances of spam by creating multiple accounts, our system is capable of handling those situations.</p>
            </div>

            <div class="bgrid">
              <h3>privacy.</h3>
              <p>In a very simple and laymans' language we have justified our Policies. Your data/information is safe and our sources are anonymous. We DO  NOT take privacy lightly.</p>
            </div>

          </div>

        </div>
        </div>
      </section>
    </div>
    <!-- end col-twelve -->
  </div>
  <!-- end row -->
</section>
<!-- end content -->

{% endblock body %}

home/templates/home/base.html
{% load static %}
{% load home_tags %}

<!-- ================================================== HEY ================================================== -->
<!--		
			# a little info about me
				- My name is Vaibhav Shukla, and I'm the creator of this site.
				- you can contribute to this project here - github.com/mr-vaibh/nerdsway
				- if you're a hacker, don't even try
-->
<!-- ============================================================================================================= -->

<!DOCTYPE html>
<!--[if IE 8]><html class="no-js oldie ie8" lang="en"> <![endif]-->
<!--[if IE 9]><html class="no-js oldie ie9" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!-->
<html class="no-js" lang="en">
	<!--<![endif]-->
	<head>
		<!--- basic page needs
		================================================== -->
		<meta charset="utf-8" />
		<meta name="viewport" content="initial-scale=1, maximum-scale=1, width=device-width, height=device-height" />
		<meta name="apple-mobile-web-app-capable" content="yes" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

		<title>{% block title %}{% endblock title %}</title>

		<!-- Google site verification -->
		<meta name="google-site-verification" content="xJGWA3r9k-uoY68neDY5c2M6h6va9qmdfJMP_CjRs30" />

		<!-- mobile specific metas
		================================================== -->
		<meta
			name="viewport"
			content="width=device-width, initial-scale=1, maximum-scale=1"
		/>

		<!-- CSS
		================================================== -->
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
		<link rel="stylesheet" href="{% static 'home/css/base.css' %}" />
		<link rel="stylesheet" href="{% static 'home/css/vendor.css' %}" />
		<link rel="stylesheet" href="{% static 'home/css/main.css' %}" />
		<link rel="stylesheet" href="{% static 'home/css/override.css' %}" />

		<!-- script
		================================================== -->
		<script src="{% static 'home/js/modernizr.js' %}"></script>
		<script src="{% static 'home/js/pace.min.js' %}"></script>

		<!-- favicons
		================================================== -->
		<link rel="shortcut icon" href="{% static 'home/images/'|add:brand_logo %}" type="image/x-icon" />
		<link rel="icon" href="{% static 'home/images/'|add:brand_logo %}" type="image/x-icon" />

		{% block meta %}{% endblock meta %}
				
		{% block head %}{% endblock head %}

		<style>
		{% block css %}{% endblock css %}
		</style>
	</head>

	<body id="top">

		<!-- header 
		================================================== -->
		{% include 'home/components/~common/navbar.html' %}
		<!-- end header -->

		{% comment %} Actual Body {% endcomment %}
		{% block body %}{% endblock body %}


		<!-- MODAL HTML -->
		<div id="subscribe_modal" class="modal">
			<!-- Modal content -->
			<div class="modal-content">
			<span class="close" id="subscribe_close">&times;</span>
			<form method="POST" action="{% url 'home:subscribe' %}" style="text-align:center;">
				{% csrf_token %}
				<h1>Get regular quality content 📃</h1>
				
				<p style="font-size:1.15em;">Subscribe to our mailing list to receive updates from the blog</p>
				<input type="email" name="subscribe_email" placeholder="your@email.plz" style="width: 100%" autocomplete="off" required>
				<button type="submit" class="button button-primary full-width">SUBSCRIBE</button>

				<p style="font-style:italics;margin:0;">PS: We promise not to spam 🤫</p>
			</form>
			</div>
		</div>
	
		<script>
		{% block js %}{% endblock js %}
		</script>

		<!-- footer
		================================================== -->
		{% include 'home/components/~common/footer.html' %}
		<!-- end footer-bottom -->

		<!-- REMOVED BECAUSE IT WAS ANNOYING
			<div id="preloader">
				<div id="loader"></div>
			</div>
		-->

		<!-- Java Script
	 	================================================== -->
		<script src="https://cdn.jsdelivr.net/npm/jdenticon@3.1.1/dist/jdenticon.min.js" async integrity="sha384-l0/0sn63N3mskDgRYJZA6Mogihu0VY3CusdLMiwpJ9LFPklOARUcOiWEIGGmFELx" crossorigin="anonymous"></script>
		<script src="{% static 'home/js/jquery-2.1.3.min.js' %}"></script>
		<script src="{% static 'home/js/plugins.js' %}"></script>
		<script src="{% static 'home/js/main.js' %}"></script>
		<script src="{% static 'home/js/custom.js' %}"></script>

		{% if not user.is_authenticated %}
		<script>
			// Ask to subscribe
			const lastModalPopup = localStorage.getItem('lastModalPopup')
			const lastDate = new Date(lastModalPopup);
			const today = new Date();

			const diffTime = Math.abs(today - lastDate);
			const diffDays = Math.ceil(diffTime / (1000 * 60 * 60 * 24)); 

			if (lastModalPopup === null || diffDays > 7) {
				setTimeout(() => {
					subscribe_link.click()
					localStorage.setItem('lastModalPopup', new Date())
				}, 3000);
			}
		</script>
		{% endif %}

	</body>
</html>

home/templates/home/contact.html
{% extends 'home/base.html' %}

{% block title %}Contact Us | {{ brand_name }}{% endblock title %}

{% block css %}
textarea {
    resize: none;
}
{% endblock css %}

{% block body %}

	<!-- content
	================================================== -->
	<section id="content-wrap" class="site-page">
		<div class="row">
			<div class="col-twelve">

				<section>

					<div class="primary-content">

						<h1 class="entry-title add-bottom">Get In Touch With Us.</h1>	

						<p class="lead">ask anything, but geniune.</p> 

						<form name="cForm" id="cForm" method="post" action="https://formspree.io/f/mqkwnzow">
							<fieldset>

								<div class="form-field">
									<input name="name" type="text" id="cName" class="full-width" placeholder="Your Name" value="">
								</div>

								<div class="form-field">
										<input name="_replyto" type="text" id="cEmail" class="full-width" placeholder="Your Email" value="">
								</div>

								<div class="form-field">
									<input name="_subject" type="text" id="cSubject" class="full-width" placeholder="Subject" value="">
								</div>

								<div class="message form-field">
									<textarea name="message" id="cMessage" class="full-width" placeholder="Your Message" ></textarea>
								</div>

								<button type="submit" class="submit button-primary full-width-on-mobile">Submit</button>

							</fieldset>
						</form> <!-- end form -->

				</section>

			</div> <!-- end col-twelve -->
			</div> <!-- end row -->		
	</section> <!-- end content -->

{% endblock body %}

home/templates/home/credits.html
{% extends 'home/base.html' %}

{% block title %}Credits | {{ brand_name }}{% endblock title %}

{% block css %}
.credit-wrapper {
    display: flex;
    flex-direction: row;
    justify-content: space-around;
}
.credit-section {
    padding-left: 2em;
}
@media all and (max-width: 768px) {
    .credit-wrapper {
        flex-direction: column;
    }
    .main {
        padding-left: 3em;
    }
}
{% endblock css %}

{% block body %}

<div class="main">
    <h1>Special Thanks to</h1>

    <div class="credit-wrapper">
        <div class="credit-section">
            <h3># Individuals and Entities</h3>
            <ul>
                <li><a target="_blank" href="https://stackoverflow.com/">Stackoverflow Community</a></li>
            </ul>
        </div>
        
        <div class="credit-section">
            <h3># Sofwares</h3>
            <ul>
                <li><a target="_blank" href="#">The the packages used in making</a></li>
                {% comment %} <li><a target="_blank" href="https://www.djangoproject.com/">Django Framework</a></li>
                <li><a target="_blank" href="https://pillow.readthedocs.io/en/stable/">Pillow library</a></li>
                <li><a target="_blank" href="https://django-tinymce.readthedocs.io/en/latest/">TinyMCE library</a></li>
                <li><a target="_blank" href="https://jdenticon.com/">Jdenticon library</a></li>
                <li><a target="_blank" href="https://django-hitcount.readthedocs.io/en/latest/">Hitcount library</a></li> {% endcomment %}
            </ul>
        </div>
    </div>

    <p class="lead">
        for their non-profit and open-source support.
    </p>
    
</div>

{% endblock body %}

home/templates/home/faq.html
{% extends 'home/base.html' %}

{% block title %}Faqs | {{ brand_name }}{% endblock title %}

{% block css %}
.collapsible {
  background-color: #777;
  color: white;
  cursor: pointer;
  padding: 18px;
  width: 100%;
  border: none;
  text-align: left;
  outline: none;
}
.collapsible:after {
  content: '\02795'; /* Unicode character for "plus" sign (+) */
  font-size: 13px;
  color: white;
  float: right;
  margin-left: 5px;
}

.active, .collapsible:hover {
  background-color: #555;
}
.active:after {
  content: "\2796"; /* Unicode character for "minus" sign (-) */
}

.primary-content p {
  padding: 0 18px;
  max-height: 0;
  overflow: hidden;
  transition: max-height 0.2s ease-out;
  background-color: #f1f1f1;
}
.primary-content a {
  text-decoration: underline;
}
{% endblock css %}

{% block body %}

<section id="content-wrap" class="site-page">
  <div class="row">
    <div class="col-twelve">
      <section>

        <div class="row content-media">
          <h1 class="entry-title col-full tab-full">Frequently Asked Questions</h1>
        </div>

        <div class="primary-content">
          {% for faq in faqs %}
          <h3 class="collapsible">{{ faq.question|capfirst }}</h3>
          {{ faq.answer | safe }}
          {% endfor %}
        </div>
              
        <p class="lead">
          Note: you can also ASK through our <a href="{% url 'home:contact' %}">contact form</a>.
        </p>

        {% if is_paginated %}
          <div class="row">
              <nav class="pagination">
                  {% if page_obj.has_previous %}
                      <a href="?page={{ page_obj.previous_page_number }}" class="page-numbers prev">Prev</a>
                  {% else %}
                      <span class="page-numbers prev inactive">Prev</span>
                  {% endif %}

                  {% for i in paginator.page_range %}
                      {% if page_obj.number == i %}
                          <span class="page-numbers current">{{ i }}</span>
                      {% else %}
                          <a href="?page={{ i }}" class="page-numbers">{{ i }}</a>
                      {% endif %}
                  {% endfor %}

                  {% if page_obj.has_next %}
                      <a href="?page={{ page_obj.next_page_number }}" class="page-numbers next">Next</a>
                  {% else %}
                      <span class="page-numbers next inactive">Next</span>
                  {% endif %}
              </nav>
          </div>
        {% endif %}
      </section>
    </div>
    <!-- end col-twelve -->
  </div>
  <!-- end row -->
</section>

{% endblock body %}


{% block js %}
const coll = document.getElementsByClassName("collapsible");
let i;

for (i = 0; i < coll.length; i++) {
  coll[i].addEventListener("click", function() {
    this.classList.toggle("active");
    var content = this.nextElementSibling;
    if (content.style.maxHeight){
      content.style.maxHeight = null;
    } else {
      content.style.maxHeight = content.scrollHeight + "px";
    } 
  });
}
{% endblock js %}

home/templates/home/index.html
{% extends 'home/base.html' %}
{% load static %}

{% block meta %}
{% include 'home/components/~common/meta.html' with meta_title="{{ brand_name }} — MrVaiBH's Official Blog" meta_desc='{{ brand_name }} is a free and open blog. Here anyone can share their stories/ideas/opinions, under the democratic conditions :)' %}
{% endblock meta %}

{% block title %}{{ brand_name }} — Personalized blogging site platform{% endblock title %}

{% block css %}
.bricks-wrapper .entry-header .entry-title {
    margin-bottom: 0;
}
.entry-meta {
    margin: 0;
    margin-top: 0.6em;
}
.entry-meta .extras * {
    font-size: 0.8em;
}
{% endblock css %}

{% block body %}

<!-- masonry
	 ================================================== -->
<section id="bricks">
	<div class="row masonry">
		<!-- brick-wrapper -->
		<div class="bricks-wrapper">
			<div class="grid-sizer"></div>

			{% include 'home/components/card/featured.html' with featured_blogs=featured_blogs %}
			
			{% for blog in blogs %}
				{% include 'home/components/card/general-card.html' with blog=blog %}
			{% endfor %}
		</div>
		<!-- end brick-wrapper -->
	</div>
	<!-- end row -->

	{% if is_paginated %}
        <div class="row">
            <nav class="pagination">
                {% if page_obj.has_previous %}
                    <a href="?page={{ page_obj.previous_page_number }}" class="page-numbers prev">Prev</a>
                {% else %}
                    <span class="page-numbers prev inactive">Prev</span>
                {% endif %}

                {% for i in paginator.page_range %}
                    {% if page_obj.number == i %}
                        <span class="page-numbers current">{{ i }}</span>
                    {% else %}
                        <a href="?page={{ i }}" class="page-numbers">{{ i }}</a>
                    {% endif %}
                {% endfor %}

                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}" class="page-numbers next">Next</a>
                {% else %}
                    <span class="page-numbers next inactive">Next</span>
                {% endif %}
            </nav>
        </div>
    {% endif %}
</section>
<!-- end bricks -->

{% endblock body %}

home/templates/home/not-found.html
{% extends 'home/base.html' %}

{% block head %}
<meta name="robots" content="noindex, nofollow" data-rh="true">
{% endblock head %}

{% block title %}
404 Page Not Found | {{ brand_name }}
{% endblock title %}

{% block body %}
{% endblock body %}

home/templates/home/subscribe.html
{% extends 'home/base.html' %}

{% block title %}{% if is_submitted %} Thank You {% else %} Subscribe to our Newsletter {% endif %} | {{ brand_name }}{% endblock title %}

{% block css %}
form {
    margin:auto;
    width: 70%;
    text-align:center;
}
#post-script {
    font-size: 1.2em;
}
{% endblock css %}

{% block body %}

<section id="content-wrap" style="padding: 0 7em;">
    {% if is_submitted %}
    
    <h1>Thanks for subscribing to our newsletter 💌</h1>
    <h3>You'll recieve regular quality content according to your taste seamlessly on <a href="mailto:{{ email }}">{{ email }}</a></h3>
    
    <br>
    
    <p id="post-script">PS: You can <a href="#">tune your recommendation</a> here</p>
    
    <a href="{% url 'home:index' %}" class="button button-primary">Back to home</a>
    
    {% else %}
    
    <form method="POST" action="{% url 'home:subscribe' %}">
        {% csrf_token %}
        <h1>Get regular quality content 📃</h1>
        
        <p style="font-size:1.15em;">Subscribe to our mailing list to receive updates from the blog</p>
        <input type="email" name="subscribe_email" placeholder="your@email.plz" style="width: 100%" autocomplete="off" required>
        <button type="submit" class="button button-primary full-width">SUBSCRIBE</button>
        
        <p style="font-style:italics;margin:0;">PS: We promise not to spam 🤫</p>
    </form>
    
    {% endif %}
</section>

{% endblock body %}

home/templates/home/support.html
<script>
window.location = "https://buymeacoffee.com/mrvaibh"
</script>

home/templates/home/tag.html
{% extends 'home/base.html' %}


{% block title %}Tag: {{ tag }} | {{ brand_name }}{% endblock title %}

{% block body %}

<!-- page header
		================================================== -->
<section id="page-header">
	<div class="row current-cat">
		<div class="col-full">
			<h1>Tag: {{ tag }}</h1>
		</div>
	</div>
</section>

<!-- masonry
		================================================== -->
<section id="bricks" class="with-top-sep">
	<div class="row masonry">
		<!-- brick-wrapper -->
		<div class="bricks-wrapper">
			<div class="grid-sizer"></div>

			{% for blog in blogs %}
			{% include 'home/components/card/general-card.html' with blog=blog %}
			{% endfor %}
			
		</div>
		<!-- end brick-wrapper -->
	</div>
	<!-- end row -->

	{% if is_paginated %}
		<div class="row">
				<nav class="pagination">
						{% if page_obj.has_previous %}
								<a href="?page={{ page_obj.previous_page_number }}" class="page-numbers prev">Prev</a>
						{% else %}
								<span class="page-numbers prev inactive">Prev</span>
						{% endif %}

						{% for i in paginator.page_range %}
								{% if page_obj.number == i %}
										<span class="page-numbers current">{{ i }}</span>
								{% else %}
										<a href="?page={{ i }}" class="page-numbers">{{ i }}</a>
								{% endif %}
						{% endfor %}

						{% if page_obj.has_next %}
								<a href="?page={{ page_obj.next_page_number }}" class="page-numbers next">Next</a>
						{% else %}
								<span class="page-numbers next inactive">Next</span>
						{% endif %}
				</nav>
		</div>
	{% endif %}
</section>
<!-- bricks -->

{% endblock body %}

home/templates/home/unsubscribe.html
{% extends 'home/base.html' %}

{% block title %}{% if is_submitted %} Nice to know you {% else %} Unsubscribe {% endif %} | {{ brand_name }}{% endblock title %}

{% block css %}
form {
    margin:auto;
    width: 70%;
    text-align:center;
}
#post-script {
    font-size: 1.2em;
}
{% endblock css %}

{% block body %}

<section id="content-wrap" style="padding: 0 7em;">
    {% if is_submitted %}
    <h1>Unsubscribed successfully, sad to see you go away 😢</h1>
    <h3>You'll no longer recieve regular quality content on <a href="mailto:{{ email }}">{{ email }}</a></h3>
    
    <br>
    
    <p id="post-script">PS: We've very responsibly deleted all your existing. So Happy Privacy 🎉</p>
    
    <a href="{% url 'home:index' %}" class="button button-primary">Back to home</a>

    {% else %}

    <form method="POST" action="{% url 'home:unsubscribe' %}">
        {% csrf_token %}
        <h1>Unsubscribe</h1>

        <p style="font-size:1.15em;">Sad to come this way 😢</p>
        <input type="email" name="unsubscribe_email" placeholder="your@email.plz" style="width: 100%" autocomplete="off" required>
        <button type="submit" class="button button-primary full-width">UNSUBSCRIBE</button>
        
        <p style="font-style:italics;margin:0;">PS: We are anytime ready to get back 😀</p>
    </form>
    {% endif %}
</section>

{% endblock body %}