account/urls.py
from django.urls import path

from django.contrib.auth import views as auth_views

from . import views

app_name = 'account'
urlpatterns = [
    path('sign-up/', views.sign_up, name='signup'),
    path('sign-in/', auth_views.LoginView.as_view(template_name='account/sign-in.html'), name='signin'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('edit/', views.UserProfileEditView.as_view(), name='user_profile_edit'),
    path('<str:user>/', views.user_profile, name='user_profile'),
    path('<str:user>/rss', views.UserRSSBlogFeedView(), name='user_rss_feed'),
]

blog/urls.py
from django.urls import path

from django.views.generic import TemplateView
from . import views

app_name = 'blog'

urlpatterns = [
    path('blog/<slug:slug>/', views.BlogDetailView.as_view(), name='detail'),
    path('blog/edit/<int:blog_id>/', views.BlogEditView.as_view(), name='edit'),
    path('blog/delete/<int:blog_id>/', views.delete_blog, name='delete'),
    path('write-new-blog/', views.BlogCreateView.as_view(), name='submit'),
    path('submit/success/', TemplateView.as_view(template_name='blog/submit-success.html'), name='submit-success'),
    path('search/<str:query>/', views.SearchBlogsListView.as_view(), name='search'),
    path('comment/<int:blog_id>/', views.comment, name='comment'),
    path('nwb/', views.NWBView.as_view(), name='nwb'),
]

home/urls.py
from django.urls import path

from django.views.generic import TemplateView
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.BlogListView.as_view(), name='index'),
    path('tag/<str:tag>/', views.TagListView.as_view(), name='tag_page'),
    path('tag/search/<str:query>/', views.tag_search, name='tag_search'),
    path('rss/', views.RSSBlogFeedView(), name='rss_feed'),
    path('subscribe/', views.subscribe, name='subscribe'),
    path('unsubscribe/', views.unsubscribe, name='unsubscribe'),
    path('about/', TemplateView.as_view(template_name='home/about.html'), name='about'),
    path('contact/', TemplateView.as_view(template_name='home/contact.html'), name='contact'),
    path('support/', TemplateView.as_view(template_name='home/support.html'), name='support'),
    path('credits/', TemplateView.as_view(template_name='home/credits.html'), name='credits'),
    path('faqs/', views.FaqListView.as_view(), name='faqs'),
    path('privacy-policy/', TemplateView.as_view(template_name='home/privacy-policy.html'), name='privacy_policy'),
    path('terms/', TemplateView.as_view(template_name='home/terms.html'), name='terms'),
]

home/models.py
from django.db import models

from django.utils.crypto import get_random_string

# Create your models here.

class Subscriber(models.Model):
    email = models.EmailField(default='', max_length=100, blank=False)
    token = models.CharField(max_length=50, default='', blank=False)
    date = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.email
    
    def save(self, *args, **kwargs):
        if not self.id:
            self.token = get_random_string(length=16)
        super(Subscriber, self).save(*args, **kwargs)

class SpecialBlog(models.Model):
    slug = models.CharField(max_length=200, blank=False, default='')
    speciality = models.CharField(choices=(('featured', 'Featured'), ('nwb', 'NWB')), max_length=50, blank=False)

    def __str__(self):
        return self.slug

class Faq(models.Model):
    question = models.CharField(max_length=200)
    answer = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.question

    class Meta:
        ordering = ('-created_at',)

home/views.py
from django.http import JsonResponse
from django.shortcuts import render
from django.views.generic import ListView
from django.contrib.syndication.views import Feed
from django.urls import reverse_lazy, reverse

from home.models import Faq, Subscriber, SpecialBlog
from blog.models import Blog, Tag

from config import BRAND_NAME

# Create your views here.

class BlogListView(ListView):
    model = Blog
    template_name = 'home/index.html'
    context_object_name = 'blogs'
    paginate_by = 10

    success_url = reverse_lazy('home:thank_you')
    success_message = 'Thanks for subscribing our newletter, stay tuned!'

    def get_queryset(self):
        # Call the base implementation first to get a context
        blogs = super(BlogListView, self).get_queryset()
        # Add extras
        blogs = blogs[:108]
        return blogs

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(BlogListView, self).get_context_data(**kwargs)
        # Add extras
        slugs = [blog.slug for blog in SpecialBlog.objects.filter(speciality='featured')]
        context['featured_blogs'] = Blog.objects.filter(slug__in=slugs)

        return context


class TagListView(ListView):
    model = Blog
    template_name = 'home/tag.html'
    context_object_name = 'blogs'
    paginate_by = 12

    def get_queryset(self):
        # Call the base implementation first to get a context
        blogs = super(TagListView, self).get_queryset()
        # Add extras
        tag = self.kwargs['tag']
        blogs = blogs.filter(tags__name__in=[tag])[:108]
        return blogs

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(TagListView, self).get_context_data(**kwargs)
        # Add extras
        context['tag'] = self.kwargs['tag']
        return context


class RSSBlogFeedView(Feed):
    title = BRAND_NAME
    link = "/blog/"
    description = f"RSS feed of {BRAND_NAME}"
 
    def items(self, user):
        return Blog.objects.all()
 
    def item_title(self, item):
        return item.title
       
    def item_description(self, item):
        from html import unescape
        from django.utils.html import strip_tags
        
        return unescape(strip_tags(item.body))
 
    def item_link(self, item):
       return reverse('blog:detail', args=[item.slug])

class FaqListView(ListView):
    model = Faq
    template_name = 'home/faq.html'
    context_object_name = 'faqs'
    paginate_by = 7

def tag_search(request, query):
    if len(query) > 2:
        data = {
            'suggestions': [tag.name for tag in Tag.objects.filter(name__icontains=query)]
        }
    else:
        data = {'suggestions': []}
    return JsonResponse(data)

def subscribe(request):
    if request.method == 'POST':
        email = request.POST.get('subscribe_email')
        
        if not Subscriber.objects.filter(email=email).exists():
            subscriber = Subscriber(email=email)
            subscriber.save()

        return render(request, 'home/subscribe.html', {'email': email, 'is_submitted': True})
    return render(request, 'home/subscribe.html')


def unsubscribe(request):
    if request.method == 'POST':
        email = request.POST.get('unsubscribe_email')
        Subscriber.objects.filter(email=email).delete()

        return render(request, 'home/unsubscribe.html', {'email': email, 'is_submitted': True})
    return render(request, 'home/unsubscribe.html')

home/templates/home/components/~common/footer.html
<footer>
  <div class="footer-main">
    <div class="row">
      <div class="col-four tab-full mob-full footer-info">
        <h4>About Our Site</h4>

        <p>
          {{ brand_name }} is a free and open blog. Here anyone can share their stories/ideas/opinions,
          under the democratic conditions. It was founded in 2022 under the holding company MRVAIBH Inc.
        </p>
      </div>
      <!-- end footer-info -->

      <div class="col-two tab-1-3 mob-1-2 site-links">
        <h4>Site Links</h4>

        <ul>
          <li><a href="{% url 'home:about' %}">About Us</a></li>
          <li><a href="{% url 'home:credits' %}">Credits</a></li>
          <li><a href="{% url 'blog:nwb' %}">NWB</a></li>
          <li><a href="{% url 'home:faqs' %}">FAQ</a></li>
          <li><a href="{% url 'home:terms' %}">Terms of Services</a></li>
          <li><a href="{% url 'home:privacy_policy' %}">Privacy Policy</a></li>
        </ul>
      </div>
      <!-- end site-links -->

      <div class="col-two tab-1-3 mob-1-2 social-links">
        <h4>Social</h4>

        <ul>
          <li><a href="{% url 'home:rss_feed' %}" target="_blank">RSS Feed</a></li>
          <li><a href="https://mrvaibh.fandom.com/wiki/NerdsWay" target="_blank">Fandom Wiki</a></li>
          <li><a href="https://twitter.com/MrVaiBH0" target="_blank">Twitter</a></li>
          <li><a href="https://facebook.com/MrVaiBH0" target="_blank">Facebook</a></li>
          <li><a href="https://instagram.com/mrvaibh0/" target="_blank">Instagram</a></li>
        </ul>
      </div>
      <!-- end social links -->

      <div class="col-four tab-1-3 mob-full footer-subscribe">
        <h4>Subscribe</h4>

        <p>Keep yourself updated. Subscribe to our newsletter.</p>

        <div class="subscribe-form">
          <form method="POST" id="mc-form" class="group" novalidate="true">
            {% comment %} <input
              type="email"
              name="subscribe_email"
              class="email"
              id="mc-email"
              placeholder="Type &amp; press enter"
              required=""
            /> {% endcomment %}

            <button type="submit" class="button button-primary full-width" name="subscribe" onclick="subscribe_modal.style.display = 'block';" >Get in touch</button>

            <label for="mc-email" class="subscribe-message"></label>
          </form>
        </div>
      </div>
      <!-- end subscribe -->
    </div>
    <!-- end row -->
  </div>
  <!-- end footer-main -->

  <div class="footer-bottom">
    <div class="row">
      <div class="col-twelve">
        <div class="copyright">
          <span>&copy; {{ brand_name }} Pvt. Ltd. <span id="current-year">XXXX</span></span>
          <span
            >Template theme credit -
            <a href="http://www.styleshout.com/" target="_blank">styleshout</a>
             (Abstract)
          </span>
        </div>

        <div id="go-top">
          <a class="smoothscroll" title="Back to Top" href="#top">
            <i class="icon icon-arrow-up"></i>
          </a>
        </div>
      </div>
    </div>
  </div>
</footer>

<script>
  document.getElementById('current-year').innerText = new Date().getFullYear();
</script>

home/templates/home/components/~common/meta.html
{% load static %}

<meta name="title" content="{{meta_title}}">
<meta name="description" content="{{meta_desc}}">
<meta name="robots" content="index, follow">

<meta property="og:url" content="{{request.build_absolute_uri}}">
<meta property="og:title" content="{{meta_title}}">
{% if meta_image %}
<meta property="og:image" content="http://{{request.get_host}}{{meta_image.url}}">
{% else %}
<meta property="og:image" content="http://{{request.get_host}}{% static 'home/images/'|add:brand_logo %}">
{% endif %}
<meta property="og:site_name" content="{{ brand_name }}">
<meta property="og:description" content="{{meta_desc}}">

<meta itemprop="name" content="{{meta_title}}">
<meta itemprop="description" content="{{meta_desc}}">
{% if meta_image %}
<meta itemprop="image" content="http://{{request.get_host}}{{meta_image.url}}">
{% else %}
<meta itemprop="image" content="http://{{request.get_host}}{% static 'home/images/'|add:brand_logo %}">
{% endif %}

<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="{{meta_title}}">
<meta name="twitter:description" content="{{meta_desc}}">
{% if meta_image %}
<meta name="twitter:image" content="http://{{request.get_host}}{{meta_image.url}}">
{% else %}
<meta name="twitter:image" content="http://{{request.get_host}}{% static 'home/images/'|add:brand_logo %}">
{% endif %}

home/templates/home/components/~common/navbar.html
{% load static %}
{% load home_tags %}

<header class="short-header">
  <div class="gradient-block"></div>

  <div class="row header-content">
    <div class="logo" onclick="window.location='/'">
      <img href="{% url 'home:index' %}"
        style="background: url('{% static "home/images/"|add:brand_logo %}') no-repeat center;
              background-size: 60px 60px;"
      />
      <span> | {% brand_name_cased %}</span>
    </div>

    {% with request.path as current_url %}
    <nav id="main-nav-wrap">
      <ul class="main-navigation sf-menu">
        <li class="{% if current_url == "/" %}current{% endif %}">
          <a href="{% url 'home:index' %}">Home</a>
        </li>
        <li class="{% if "nwb" in current_url %}current{% endif %}">
          <a href="{% url 'blog:nwb' %}">NWB</a>
        </li>
        <li class="{% if "about" in current_url %}current{% endif %}">
          <a href="{% url 'home:about' %}">About</a>
        </li>
        <li class="{% if "contact" in current_url %}current{% endif %}">
          <a href="{% url 'home:contact' %}">Contact</a>
        </li>
        <li class="{% if "support" in current_url %}current{% endif %}">
          <a href="{% url 'home:support' %}">Support</a>
        </li>
        <li class="{% if "faq" in current_url %}current{% endif %}">
          <a href="{% url 'home:faqs' %}">FAQ</a>
        </li>
        <li class="{% if "subscribe" in current_url %}current{% endif %}">
          <span id="subscribe_link">SUBSCRIBE</span>
        </li>
        {% if request.user.is_authenticated %}
        <li class="has-children {% if "myprofile" in current_url %}current{% endif %}">
          <a href="#">Me</a>
          <ul class="sub-menu">
            <li><a href="{% url 'blog:submit' %}">Write a Blog</a></li>
            <li><a href="{% url 'account:user_profile' user=request.user %}">Profile</a></li>
            <hr>
            <li><a href="{% url 'account:logout' %}">Logout</a></li>
          </ul>
        </li>
        {% else %}
        <li class="{% if "sign-in" in current_url %}current{% endif %}">
          <a href="{% url 'account:signin' %}">Login</a>
        </li>
        <li class="{% if "sign-up" in current_url %}current{% endif %}">
          <a href="{% url 'account:signup' %}">Register</a>
        </li>
        {% endif %}
      </ul>
    </nav>
    {% endwith %}
    <!-- end main-nav-wrap -->

    <div class="search-wrap">
      <form class="search-form" id="search-form">
        <label>
          <span class="hide-content">Search for:</span>
          <input
            type="search"
            class="search-field"
            id="search-field"
            placeholder="Type Your Keywords"
            value=""
            name="s"
            title="Search for:"
            autocomplete="off"
          />
        </label>
        <input type="submit" class="search-submit" value="Search" />
      </form>

      <a href="#" id="close-search" class="close-btn">Close</a>
    </div>
    <!-- end search wrap -->

    <div class="triggers">
      <a class="search-trigger" href="#"><i class="fa fa-search"></i></a>
      <a class="menu-toggle" href="#"><span>Menu</span></a>
    </div>
    <!-- end triggers -->
  </div>
</header>