account/urls.py
from django.urls import path

from django.contrib.auth import views as auth_views

from . import views

app_name = 'account'
urlpatterns = [
    path('sign-up/', views.sign_up, name='signup'),
    path('sign-in/', auth_views.LoginView.as_view(template_name='account/sign-in.html'), name='signin'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('edit/', views.UserProfileEditView.as_view(), name='user_profile_edit'),
    path('<str:user>/', views.user_profile, name='user_profile'),
    path('<str:user>/rss', views.UserRSSBlogFeedView(), name='user_rss_feed'),
]

blog/urls.py
from django.urls import path

from django.views.generic import TemplateView
from . import views

app_name = 'blog'

urlpatterns = [
    path('blog/<slug:slug>/', views.BlogDetailView.as_view(), name='detail'),
    path('blog/edit/<int:blog_id>/', views.BlogEditView.as_view(), name='edit'),
    path('blog/delete/<int:blog_id>/', views.delete_blog, name='delete'),
    path('write-new-blog/', views.BlogCreateView.as_view(), name='submit'),
    path('submit/success/', TemplateView.as_view(template_name='blog/submit-success.html'), name='submit-success'),
    path('search/<str:query>/', views.SearchBlogsListView.as_view(), name='search'),
    path('comment/<int:blog_id>/', views.comment, name='comment'),
    path('nwb/', views.NWBView.as_view(), name='nwb'),
]

home/urls.py
from django.urls import path

from django.views.generic import TemplateView
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.BlogListView.as_view(), name='index'),
    path('tag/<str:tag>/', views.TagListView.as_view(), name='tag_page'),
    path('tag/search/<str:query>/', views.tag_search, name='tag_search'),
    path('rss/', views.RSSBlogFeedView(), name='rss_feed'),
    path('subscribe/', views.subscribe, name='subscribe'),
    path('unsubscribe/', views.unsubscribe, name='unsubscribe'),
    path('about/', TemplateView.as_view(template_name='home/about.html'), name='about'),
    path('contact/', TemplateView.as_view(template_name='home/contact.html'), name='contact'),
    path('support/', TemplateView.as_view(template_name='home/support.html'), name='support'),
    path('credits/', TemplateView.as_view(template_name='home/credits.html'), name='credits'),
    path('faqs/', views.FaqListView.as_view(), name='faqs'),
    path('privacy-policy/', TemplateView.as_view(template_name='home/privacy-policy.html'), name='privacy_policy'),
    path('terms/', TemplateView.as_view(template_name='home/terms.html'), name='terms'),
]

blog/models.py
from django.db import models
from django.contrib.contenttypes.fields import GenericRelation
from hitcount.models import HitCount, HitCountMixin

from django.dispatch import receiver
from django.db.models.signals import post_save

from tinymce.models import HTMLField

from django.template.defaultfilters import slugify
from django.utils.crypto import get_random_string
from django.urls import reverse

from datetime import datetime

# Create your models here.

class Tag(models.Model):
    name = models.CharField(max_length=50, unique=True, null=False)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.name = self.name.lower()
        return super(Tag, self).save(*args, **kwargs)

    class Meta:
        ordering = ['name']
        verbose_name_plural = 'Tags'


class BlogQuerySet(models.QuerySet):
    def search(self, **kwargs):
        queryset = self

        search_query = kwargs.get('query', None)
        queryset = (queryset.filter(title__icontains=search_query) | queryset.filter(body__icontains=search_query) | queryset.filter(tags__name__in=[search_query]))

        sort_by = kwargs.get('sort_by', '')
        date_from = kwargs.get('date_from', '')
        date_to = kwargs.get('date_to', '')

        if sort_by == 'popular':
            queryset = queryset.order_by('-hit_count_generic__hits')
        elif sort_by == 'newest':
            queryset = queryset.order_by('-date')
        elif sort_by == 'oldest':
            queryset = queryset.order_by('date')
        
        if date_from and date_to:
            queryset = queryset.filter(date__range=(date_from, date_to))
        return queryset

class Blog(models.Model, HitCountMixin):
    objects = BlogQuerySet.as_manager()

    hit_count_generic = GenericRelation(HitCount, object_id_field='object_pk', related_query_name='hit_count_generic_relation')
    title = models.CharField(max_length=100)
    tags = models.ManyToManyField(Tag, blank=True, related_name='tag')
    slug = models.SlugField(default='', editable=False, max_length=200, null=False, unique=True)
    body = HTMLField()
    excerpt = models.TextField(max_length=500, blank=True)
    show_excerpt_in_blog = models.BooleanField(default=True)
    date = models.DateField(auto_now_add=True)
    time = models.TimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    thumb = models.ImageField(blank=True, upload_to='blog/blog_thumbs')
    thumb_alt = models.CharField(max_length=50, default='', blank=True)

    def __str__(self):
        return self.title

    def snippet(self):
        return self.body[:50] + '...'
    
    def get_datetime(self):
        return datetime.combine(self.date, self.time)
    
    def get_read_time(self):
        from html import unescape
        from django.utils.html import strip_tags
        
        string = self.title + unescape(strip_tags(self.body))
        total_words = len((string).split())

        return round(total_words / 200)

    def get_absolute_url(self):
        return reverse('blog:detail', kwargs={'slug': self.slug})

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.title + '--' +
                                get_random_string(length=7))
        super(Blog, self).save(*args, **kwargs)

    class Meta:
        ordering = ['-date']

@receiver(post_save, sender=Blog)
def send_newsletter(sender, instance, created, **kwargs):
    if created:
        from django.core.mail import EmailMultiAlternatives
        from django.template.loader import render_to_string
        from html import unescape
        from django.utils.html import strip_tags
        from home.models import Subscriber

        mailing_list = [email for email in Subscriber.objects.values_list('email', flat=True)]

        html_content = render_to_string('account/email_template.html', {
            'title': instance.title,
            'content': unescape(instance.body),
        })
        text_content = strip_tags(html_content)

        email = EmailMultiAlternatives(
            instance.title,
            text_content,
            '',
            mailing_list,
        )
        email.attach_alternative(html_content, "text/html")
        email.send()

class Comment(models.Model):
    user = models.ForeignKey('auth.User', on_delete=models.CASCADE, blank=False)
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, related_name='blog')
    body = models.TextField()
    datetime = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.body[:50]

    class Meta:
        ordering = ['-datetime']

blog/forms.py
from cProfile import label
from django.forms import ModelForm, Textarea, CharField
from django.utils.translation import gettext_lazy as _


from tinymce.widgets import TinyMCE
from .models import Blog, Comment

class BlogForm(ModelForm):
    body = CharField(widget=TinyMCE(), label='Write your blog, (fullscreen mode available)')

    class Meta:
        model = Blog
        exclude = ['author', 'tags']
        field_requireds = {
            'title': _('Title is required.'),
            'body': _('Body is required.'),
        }
        labels = {
            'thumb' : 'Thumbnail',
            'thumb_alt': 'Thumbnail Description (optional)',
        }
        widgets = {
            'excerpt': Textarea(attrs={'style': 'min-height: unset;height: 180px;'}),
        }

blog/views.py
from django.http import Http404, HttpResponseNotAllowed
from django.shortcuts import redirect
from django.views.generic import ListView, CreateView, UpdateView
from django.contrib.messages.views import SuccessMessageMixin
from hitcount.views import HitCountDetailView
from django.urls import reverse_lazy

from django.contrib.auth.models import User
from .forms import BlogForm

from home.models import SpecialBlog
from .models import Blog, Comment, Tag


class BlogDetailView(HitCountDetailView):
    model = Blog
    template_name = 'blog/single-standard.html'
    context_object_name = 'blog'
    count_hit = True
    
    def get_context_data(self, **kwargs):
        context = super(BlogDetailView, self).get_context_data(**kwargs)
        context['comments'] = Comment.objects.filter(blog=self.get_object())
        return context
        

class SearchBlogsListView(ListView):
    model = Blog
    template_name = 'blog/search-blogs.html'
    paginate_by = 10
    context_object_name = 'blogs'
    
    def get_queryset(self):
        blogs = super(SearchBlogsListView, self).get_queryset()
        params = {
            'query': self.kwargs.get('query'),
            'sort_by': self.request.GET.get('sort_by'),
            'date_from': self.request.GET.get('date_from'),
            'date_to': self.request.GET.get('date_to'),
        }
        blogs = Blog.objects.search(**params)
        
        return blogs
    
    def get_context_data(self, **kwargs):
        context = super(SearchBlogsListView, self).get_context_data(**kwargs)
        context['query'] = self.kwargs.get('query', None)
        context['filters'] = {
            'sort_by': self.request.GET.get('sort_by', ''),
            'date_from': self.request.GET.get('date_from', ''),
            'date_to': self.request.GET.get('date_to', ''),
        }
        return context

class BlogCreateView(SuccessMessageMixin, CreateView):
    model = Blog
    form_class = BlogForm
    template_name = 'blog/submit-blog.html'
    context_object_name = 'blog'
    success_url = reverse_lazy('blog:submit-success')
    success_message = 'Your blog has been created successfully'

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            form.instance.author = User.objects.get(username=request.user)
            form.instance.save()

            # Adding Tags
            tags_string = self.request.POST.get('tags', '')
            tags = [x.strip() for x in tags_string.split(',') if x.strip()]

            for tag in tags:
                try:
                    tag_obj = Tag.objects.get(name=tag)
                    form.instance.tags.add(tag_obj)
                except Tag.DoesNotExist:
                    form.instance.tags.create(name=tag)
            
            return self.form_valid(form)


class BlogEditView(UpdateView):
    model = Blog
    form_class = BlogForm
    template_name = 'blog/edit-blog.html'
    context_object_name = 'blog'
    pk_url_kwarg = 'blog_id'

    def post(self, request, *args, **kwargs):
        # Updating Tags (first clearing all tags then adding them each)
        self.get_object().tags.clear()
        tags_string = self.request.POST.get('tags', '')
        tags = [x.strip() for x in tags_string.split(',') if x.strip()]

        for tag in tags:
            try:
                tag_obj = Tag.objects.get(name=tag)
                self.get_object().tags.add(tag_obj)
            except Tag.DoesNotExist:
                self.get_object().tags.create(name=tag)
        return super().post(request, *args, **kwargs)

    def get_success_url(self):
        return reverse_lazy('blog:detail',
                            current_app='blog',
                            kwargs={'slug': self.get_object().slug})

class NWBView(ListView):
    model = Blog
    template_name = 'blog/nwb.html'
    context_object_name = 'blogs'

    def get_queryset(self):
        slugs = [blog.slug for blog in SpecialBlog.objects.filter(speciality='nwb')]
        return Blog.objects.filter(slug__in=slugs)

def delete_blog(request, blog_id):
    if not request.user.is_authenticated:
        return redirect(reverse_lazy('account:signin'))
    
    if request.method == 'POST':
        Blog.objects.filter(id=blog_id).delete()
        return redirect(reverse_lazy('account:user_profile', kwargs={'user': request.user}) + '?tab=blogs')
    
    return HttpResponseNotAllowed('Method not allowed')

def comment(request, blog_id):
    blog_object = Blog.objects.get(id=blog_id)

    if request.method == 'POST' and request.user.is_authenticated:
        body = request.POST.get('comment_body', '')    
        Comment.objects.create(user=request.user, blog=blog_object, body=body)

    return redirect(reverse_lazy('blog:detail', kwargs={'slug': blog_object.slug}))

blog/templates/blog/edit-blog.html
{% extends 'home/base.html' %}
{% load static %}
{% load account_tags %}

{% block title %}Edit Blog | {{ brand_name }}{% endblock title %}

{% block head %}
{% comment %} {{ form.media }} {% endcomment %}
<script src="{% static 'django_tinymce/init_tinymce.js' %}" referrerpolicy="origin"></script>
<script src="https://cdn.tiny.cloud/1/0kuyakq1c4gvk3f0dvr88cyg9lydia7r0et1z5c6owxz1ac9/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
<link rel="stylesheet" href="{% static 'blog/css/blog.css' %}">
{% endblock head %}

{% block body %}

<section id="content-wrap">
    <div class="row">
        
        {% if form.errors %}
        <div class="alert-box ss-error hideit">
            <p>{{form.errors}}</p>
            <i class="fa fa-times close"></i>
        </div>
        {% endif %}

        <br />
        
        <div class="col-twelve">
            <form action="{% url 'blog:edit' blog_id=blog.id %}" method="post" enctype="multipart/form-data" autocomplete="off">
            {% csrf_token %}
            
            {% for element in form %}
                <div class="form-group">
                    <label for="title">{{element.label}}</label>
                    {{element}}
                </div>
            {% endfor %}

            <div class="form-group" style="position: relative;">
                <label for="tags">Start typing to add tags:</label>
                <input type="text" id="addTagInput">
                <div id="tagSuggestions">
                    <ul>
                        {% comment %} <li><a href="#">tag</li> {% endcomment %}
                    </ul>
                </div>
                
                <div id="tagPills">
                    {% comment %} <span class="pill">abc <span class="remove">&times;</span></span> {% endcomment %}
                </div>
                <input type="hidden" name="tags" id="tagsInput" value="{% for tag in blog.tags.all %}{{ tag }}&#44;{% endfor %}">
            </div>
            
            <br />
            <br />
            
            <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>
</section>

<script src="{% static 'blog/js/tag-dropdown.js' %}"></script>

{% endblock body %}

blog/templates/blog/search-articles.html
{% extends 'home/base.html' %}

{% block title %}
Search: {{query}} | NerdsWay
{% endblock title %}

{% block css %}
.filters {;
    display: flex;
    flex-direction: row;
    justify-content: space-between;
    margin-bottom: 1em;
}
.filters h3 {
    margin-left: 0.8em;
    margin-right: 0.8em;
}
.filters select, .filters button {
    height: 2em;
    line-height: unset;
    padding: 0 1em 0 1em;
    width: 10em;
}
.filters button {
    margin-left: 0.8em;
    margin-right: 0.8em;
}
.filters input::active {
    background-color: #fafafa;
}

.blog {
    display: flex;
    flex-direction: row;
}

.blog img {
    width: 10em;
    height: 10em;
}

.blog-details {
    margin-left: 1em;
}

.blog-details p {
    margin-bottom: 1em;
}
.blog-details p.read-more {
    margin-bottom: 0;
}

@media (max-width: 768px) {    
    .blog img {
        width: 5em;
        height: 5em;
    }

    .blog-details {
        margin-left: 0.5em;
    }

    .blog-details h2 {
        font-size: 1.2em;
        margin-bottom: 0;
    }
    .blog-details p {
        font-size: 0.7em;
        line-height: 1.5em;
        margin-bottom: 0;
    }
    .blog-details .extras {
        font-size: 0.7em;
    }
}

{% endblock css %}

{% block body %}

    <div class="main">
        <form class="filters" action="{% url 'blog:search' query=query %}">
            <h3>Filters:</h3>
            <select name="sort_by" id="filter">
                <option value="">default</option>
                <option value="popular" {% if filters.sory_by == "popular" %}selected{% endif %}>popular</option>
                <option value="newest" {% if filters.sort_by == "newest" %}selected{% endif %}>newest first</option>
                <option value="oldest" {% if filters.sort_by == "oldest" %}selected{% endif %}>oldest first</option>
            </select>
            
            <h3>Range:</h3>
            <input type="date" name="date_from" value="{{filters.date_from}}">
            <h3>to</h3>
            <input type="date" name="date_to" value="{{filters.date_to}}">
            <button class="button-primary" type="submit">Apply</button>
        </form>

        <h1> {{blogs|length}} search result{{blogs|length|pluralize}} found for '{{query}}':</h1>

        {% if blogs|length == 0 %}
        <h1>Try searching in date range</h1>
        {% endif %}

        {% for blog in blogs %}
            <div class="blog">
                {% if blog.thumb %}
                    <img src="{{blog.thumb.url}}" alt="{{blog.thumb_alt}}">
                {% endif %}
                <div class="blog-details">
                    <h2><a href="{% url 'blog:detail' slug=blog.slug %}">{{blog.title}}</a></h2>
                    <p class="body">
                    {% if blog.show_excerpt %}
                        {{blog.excerpt}}
                    {% else %}
                        {{blog.body|striptags|truncatechars:255}}
                    {% endif %}
                    </p>
                    <p class="read-more">
                        <a href="{% url 'blog:detail' slug=blog.slug %}">Read more</a>
                    </p>

                    <span class="extras">
                        <span class="date">{{blog.get_datetime|date:"d M Y \a\t h:m a"}}</span>
                        by
                        <span class="author">
                            <a href="{% url 'account:user_profile' user=blog.author %}">{{blog.author.userprofile.get_full_name}}</a>
                        </span>
                    </span>
                </div>
            </div>

            <hr>
        {% endfor %}

        {% if is_paginated %}
        <div class="row">
            <nav class="pagination">
                {% if page_obj.has_previous %}
                    <a href="{% url 'blog:search' query=query %}?page={{ page_obj.previous_page_number }}" class="page-numbers prev">Prev</a>
                {% else %}
                    <span class="page-numbers prev inactive">Prev</span>
                {% endif %}

                {% for i in paginator.page_range %}
                    {% if page_obj.number == i %}
                        <span class="page-numbers current">{{ i }}</span>
                    {% else %}
                        <a href="{% url 'blog:search' query=query %}?page={{ i }}" class="page-numbers">{{ i }}</a>
                    {% endif %}
                {% endfor %}

                {% if page_obj.has_next %}
                    <a href="{% url 'blog:search' query=query %}?page={{ page_obj.next_page_number }}" class="page-numbers next">Next</a>
                {% else %}
                    <span class="page-numbers next inactive">Next</span>
                {% endif %}
            </nav>
        </div>
        {% endif %}

    </div>

{% endblock body %}

blog/templates/blog/single-standard.html
{% extends 'home/base.html' %}
{% load humanize %}
{% load hitcount_tags %}
{% load account_tags %}

{% block meta %}
{% include 'home/components/~common/meta.html' with meta_title=blog.title meta_desc=blog.body|striptags|truncatechars:150 meta_image=blog.thumb %}
{% endblock meta %}

{% block title %}
{{ blog.title }} | by {{blog.author.userprofile.get_full_name}} | {{ brand_name }}
{% endblock title %}

{% block css %}
#content-wrap .entry-title, #content-wrap .page-title {
	font-size: 2.4em;
}
textarea {
	min-height: 12rem;
}
.commentlist li .comment-info a {
	color: #000000;
}
.commentlist li .comment-text {
	margin: 0;
}
{% endblock css %}

{% block body %}
	<!-- content
	================================================== -->
	<section id="content-wrap" class="blog-single">
		<div class="row">
			<div class="col-twelve">

				<article class="format-standard">  
				
					{% if blog.thumb %}
					<div class="content-media">
						<div class="post-thumb">
							<img src="{{blog.thumb.url}}" alt="{{blog.thumb_alt}}" style="max-height: 20em;">
						</div>
					</div>
					{% endif %}

					<div class="primary-content">

						<h1 class="page-title">{{blog.title}}</h1>

						<ul class="entry-meta">
							{% user_name blog.author href=True %}
							- <li class="date">{{blog.get_datetime |date:"F j, Y, g:i a"}}</li>
							
							<br>
							
							<span style="color: #000000;">
								{% get_hit_count for blog as views %}
								<i class="fa-solid fa-eye"></i> {{ views |intcomma }} view{{ views |pluralize }}
								&nbsp;&nbsp;
								<i class="fa-solid fa-clock"></i> {{ blog.get_read_time }} mins read
								{% if blog.author == request.user %}
								&nbsp;&nbsp;
								<span onclick="window.location='{% url 'blog:edit' blog_id=blog.id %}';"><i class="fa-solid fa-pen-to-square"></i> Edit</span>
								&nbsp;&nbsp;
								<span id="confirm_link"><i class="fa-solid fa-trash"></i> Delete</span>
								{% endif %}

								<!-- DELETE MODAL HTML -->
								<div id="confirm_modal" class="modal">
									<!-- Modal content -->
									<div class="modal-content">
										<span class="close" id="confirm_close">&times;</span>
										<form method="POST" action="{% url 'blog:delete' blog_id=blog.id %}" style="text-align:center;">
											{% csrf_token %}
											<h1>Are you sure?</h1>
											
											<p style="font-size:1.15em;">This step is irreversible, do you really wanna continue?</p>
											<button type="submit" class="button button-primary full-width">CONFIRM DELETE</button>
										</form>
									</div>
								</div>
							</span>

						</ul>

						<div class="entry-excerpt">
							{% if blog.show_excerpt_in_blog %}
							<p class="lead">{{blog.excerpt}}</p>
							{% endif %}
						</div>

						{{blog.body | safe}}

						{% if blog.tags.all %}
						<p class="tags">
							<span>Tagged in :</span>
							{% for tag in blog.tags.all %}
							<a href="{% url 'home:tag_page' tag=tag %}">{{tag}}</a>
							{% endfor %}
						</p>
						{% endif %}

						{% with blog.author.userprofile as author %}
							<div class="author-profile">
								{% profile_pic blog.author %}

								<div class="about">
									<h4>{% user_name blog.author href=True %}</h4>

									<p>{{author.bio}}</p>

									<ul class="author-social">
										{% if author.facebook %}
										<li><a target="_blank" href="https://facebook.com/{{author.facebook}}">Facebook</a></li>
										{% endif %}
										{% if author.twitter %}
										<li><a target="_blank" href="https://twitter.com/{{author.twitter}}">Twitter</a></li>
										{% endif %}
										{% if author.instagram %}
										<li><a target="_blank" href="https://instagram.com/{{author.instagram}}">Instagram</i></a></li>					        	
										{% endif %}
										{% if author.website %}
										<li><a target="_blank" href="{{author.website}}">Website</a></li>
										{% endif %}
									</ul>
								</div>
							</div> <!-- end author-profile -->						
						{% endwith %}

					</div> <!-- end entry-primary -->

				</article>

			<br><br>

			</div> <!-- end col-twelve -->
		</div> <!-- end row -->

		<div class="comments-wrap">
			<div id="comments" class="row">
				<div class="col-full">

					<h3>{{ comments|length }} Comment{{ comments|length|pluralize }} </h3>

					<!-- commentlist -->
					<ol class="commentlist">
					{% for comment in comments %}
					<li class="depth-1">

						<div class="avatar">
						{% if comment.user %}
							{% profile_pic comment.user %}
						{% else %}
							<svg data-jdenticon-value="{{ comment.email }}" title="this image is unique for your Email ID"></svg>
						{% endif %}
						</div>

						<div class="comment-content">

							<div class="comment-info">
								<cite>{% user_name comment.user href=True %}</cite>

								<div class="comment-meta">
								<time class="comment-time" datetime="2014-07-12T23:05">{{ comment.datetime |date:"F j, Y @ g:i a"}} </time>
								</div>
							</div>

							<div class="comment-text">
								<p>{{ comment.body }}</p>
							</div>

						</div>

					</li>
					{% endfor %}

					</ol> <!-- Commentlist End -->

					<!-- respond -->
					<div class="respond">
						{% if request.user.is_authenticated %}
						<h3>Leave a Comment</h3>
						
						<form name="contactForm" id="contactForm" method="post" action="{% url 'blog:comment' blog_id=blog.id %}">
							{% csrf_token %}
							<fieldset>
								<div class="message form-field">
									<textarea name="comment_body" id="cMessage" class="full-width" placeholder="Your Message" required></textarea>
								</div>
								
								<button type="submit" class="submit button-primary">Submit</button>
							</fieldset>
						</form> <!-- Form End -->
						{% else %}
						<h3>You're be authorised leave a comment</h3>
						
						<button type="button" class="button-secondary" onclick="window.location=`{% url 'account:signin' %}`;">Login</button>
						<button type="button" class="button-primary" onclick="window.location=`{% url 'account:signup' %}`;">Signup</button>
						{% endif %}

					</div> <!-- Respond End -->
				</div> <!-- end col-full -->
			</div> <!-- end row comments -->
		</div> <!-- end comments-wrap -->

	 </section> <!-- end content -->

{% endblock body %}

{% block js %}
// confirm delete modal
const confirm_modal = document.getElementById("confirm_modal");
const confirm_btn = document.getElementById("confirm_link");
const confirm_close = document.getElementById("confirm_close");

confirm_btn.onclick = function() {
	confirm_modal.style.display = "block";
}
confirm_close.onclick = function() {
	confirm_modal.style.display = "none";
}
window.onclick = function(event) {
	if (event.target == confirm_modal) {
		confirm_modal.style.display = "none";
	}
}
{% endblock js %}

blog/templates/blog/submit-blog.html
{% extends 'home/base.html' %}
{% load static %}
{% load account_tags %}

{% block title %}Write a Blog | {{ brand_name }}{% endblock title %}

{% block head %}
{% comment %} {{ form.media }} {% endcomment %}
<script src="{% static 'django_tinymce/init_tinymce.js' %}" referrerpolicy="origin"></script>
<script src="https://cdn.tiny.cloud/1/0kuyakq1c4gvk3f0dvr88cyg9lydia7r0et1z5c6owxz1ac9/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
<link rel="stylesheet" href="{% static 'blog/css/blog.css' %}">
{% endblock head %}

{% block css %}
.alert .danger {
    color: red
}
input, textarea {
    width: 100%;
}
form [type=checkbox] {
    width: 20px;
    height: 20px;
}

#id_body {
    background-color: unset;
}

{% endblock css %}

{% block body %}

<section id="content-wrap">
    <div class="row">
        
        {% if form.errors %}
        <div class="alert-box ss-error hideit">
            <p>{{form.errors}}</p>
            <i class="fa fa-times close"></i>
        </div>
        {% endif %}

        <br />
        
        <div class="col-twelve">
            <form action="{% url 'blog:submit' %}" method="post" enctype="multipart/form-data" autocomplete="off">
            {% csrf_token %}
            
            {% for element in form %}
                <div class="form-group">
                    <label for="title">{{element.label}}</label>
                    {{element}}
                </div>
            {% endfor %}

            <div class="form-group" style="position: relative;">
                <label for="tags">Start typing to add tags:</label>
                <input type="text" id="addTagInput">
                <div id="tagSuggestions">
                    <ul>
                        {% comment %} <li><a href="#">tag</li> {% endcomment %}
                    </ul>
                </div>
                
                <div id="tagPills">
                    {% comment %} <span class="pill">abc <span class="remove">&times;</span></span> {% endcomment %}
                </div>
                <input type="hidden" name="tags" id="tagsInput">
            </div>
            
            <br />
            <br />
            
            <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>
</section>

<script src="{% static 'blog/js/tag-dropdown.js' %}"></script>

{% endblock body %}

blog/templates/blog/submit-success.html
{% extends 'home/base.html' %}

{% block title %}Blog Created Successfully | {{ brand_name }}{% endblock title %}

{% block body %}

<section id="content-wrap" style="padding: 0 7em;">
    {% if messages %}
        {% for message in messages %}
            <h1>{{ message|safe }}</h1>
        {% endfor %}
    {% else %}
        <script>window.location="{% url 'blog:submit' %}"</script>
    {% endif %}
</section>

{% endblock body %}